before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: J23D5BmkvToakNUdjaZv9/mmV9bkZhzj8F+FIvqYU8qXWyxYIyHg5htu7CsiTKeF7A3l/nPdTer4WPBfzaxkH1giyoH4iQ5G23L3EeZ2L2T/adQW5ibTQgJH6b0tJkl+3GgSyrY1mkrcICMMTmMAq3KBTgjjpas+wiPENNejOkRQtLsj1JHhfJpKfY9G4O95lQWfwnyuwqU7Pi2+18ErHcUFC+YhWldnbMdxqggR+McWhhoVBPsiAIl2oVWpKAl5198LlcKPn+PYDs/XB+CF+t4CHxWhWNzIbFl0CCfSFxvHjH1RImXerhixXmTYAkweVDexrNDqiv0Dx4GNSzA2H8gsPiKi02ZJDbI0Oo2YpIUQJfpQefrDzc8WgA0VQzgD7Xcs8HbxcKr45pJHyK+zBBVUMWsm9KSVUGK3/P1yf59C5wU+YWe1+ZTZjZoa7eWet96Jl7NLkovQNmk9ufEHGmm90H3aHG84ByBVJDg4EEIMUdumx1AIo3nLQ4bp1Vsz1M3+IRxgC2z+fDUIwT3O5yrlmoNTyzzThM4k83pKtA4rXf0l1UnmcVtiMRt2PcuknU+ORxf4q8K1F5lXX5DYpbzvojKW8d5R6B1CXszW2W6DWbTYTCE1IU/kFG9n30/IqGGnGS55Vt8GTxLRO1dpESRXDcY3Iil+xg2jfKyGAms= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    # - 6
    - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
